### ISSUE TITLE
Is this code available?

### ISSUE THREAD

**Issue by fifteenhex** [directfb2/DFBTerm#2]
Hi,

Would it be possible to push this code?

**Comment by caramelli** [comment]
The last official version of DFBTerm was 0.8.15. So if you search for the DFBTerm-0.8.15.tar.gz tarball, you should be able to find the source code. It's quite old and not directly usable... That's why the repository is still empty, but yes, I plan to revive this project and push the code.

**Comment by caramelli** [comment]
DFBTerm code has been restored.
